        import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/ThemeProvider"
import Navbar from "@/components/main compo/header/Navbar";
import { auth } from "@/auth"
import { AuthProvider } from "@/components/ui/AuthProvider";
import Footer from "@/components/main compo/hero/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CODE BLOG APP",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {const session = await auth();
  return (
    <html
      lang="en" suppressHydrationWarning
     
    >
      <body className="min-h-full">
        <AuthProvider>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar user={session?.user}  />
        <main>
        { children}
</main>
<Footer/>

              </ThemeProvider>
              </AuthProvider>
        </body>
      </html>
  );
}
